### ISSUE TITLE
Amazing stuff! 

### ISSUE THREAD

**Issue by abhinavgudipati** [watch24hrs-iiitd/Stress-Test#1]
well coded bro! it would be great if you could share the intuition behind how you were able to come up with this! 
thanking you in anticipation!

**Comment by dv-rastogi** [comment]
Thanks, Abhinav! 
So what do you mean by "the intuition" behind it? Are you talking in reference to what stress testing is? Or are you talking about how did I write a stress testing script? Let me know & I would be happy to reply!

**Comment by abhinavgudipati** [comment]
Yeah, precisely how you were able to *code* the stress testing script! 
thanking you in anticipation :)

**Comment by dv-rastogi** [comment]
I guess stress testing would be a fancy way of saying that you are comparing two outputs of different programs which are "supposed" to be producing the same output for a given set of input. In essence, comparing your brute solutions against optimized solutions. 
- I am generating a particular input format using [this function](https://github.com/watch24hrs-iiitd/Stress-Test/blob/102f9d55b024b711d620ac4f558693e6e68e052a/stressCheck.py#L26) & then asking the user for certain parameters that if he/she wants to know where the difference in their output occurred and other customizable stuff. 
- And then finally just invoking both brute & optimized executables in order to compare the output [here](https://github.com/watch24hrs-iiitd/Stress-Test/blob/102f9d55b024b711d620ac4f558693e6e68e052a/stressCheck.py#L55)! 
So I guess this would sum it up! Does the same work out for you?

**Comment by abhinavgudipati** [comment]
Yooo, I will get back to you on this post the midsems yeah? So sorry I did not follow up! thanks for the concern tho..
